# fly.toml app configuration file generated for textural on 2024-05-18T18:28:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'textural'
primary_region = 'lhr'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data"
  destination = "/app/arc"

[[services]]
  internal_port = 8080
  [[services.ports]]
    handlers = ["tls"]
    port = 443
